# --------------------------------------
# -- Join worker kubernetes node
# --------------------------------------Ã
- name: Join worker node
  shell: >
    {{ kubernetes_join_command }}
    creates=/etc/kubernetes/kubelet.conf

